export const EXTENSIONS_ENUM = {
  '.7z': 'application/x-7z-compressed',
  '.aac': 'audio/aac',
  '.avi': 'video/x-msvideo',
  '.avif': 'image/avif',
  '.aiff': 'audio/x-aiff',
  '.bmp': 'image/bmp',
  '.bz2': 'application/x-bzip2',
  '.css': 'text/css',
  '.csv': 'text/csv',
  '.doc': 'application/msword',
  '.docx': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  '.eot': 'application/vnd.ms-fontobject',
  '.flac': 'audio/flac',
  '.gif': 'image/gif',
  '.gz': 'application/gzip',
  '.heic': 'image/heic',
  '.heif': 'image/heif',
  '.htm': 'text/html',
  '.html': 'text/html',
  '.ico': 'image/x-icon',
  '.jpg': 'image/jpeg',
  '.json': 'application/json',
  '.jsonld': 'application/ld+json',
  '.js': 'text/javascript',
  '.md': 'text/markdown',
  '.m4a': 'audio/m4a',
  '.mkv': 'video/x-matroska',
  '.mov': 'video/quicktime',
  '.mp3': 'audio/mpeg',
  '.mp4': 'video/mp4',
  '.ogg': 'audio/ogg',
  '.opus': 'audio/opus',
  '.otf': 'application/font-sfnt',
  '.pdf': 'application/pdf',
  '.png': 'image/png',
  '.ppt': 'application/vnd.ms-powerpoint',
  '.pptx': 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
  '.rar': 'application/x-rar-compressed',
  '.svg': 'image/svg+xml',
  '.tar': 'application/x-tar',
  '.tiff': 'image/tiff',
  '.ttf': 'application/font-sfnt',
  '.txt': 'text/plain',
  '.wav': 'audio/wav',
  '.webm': 'video/webm',
  '.webp': 'image/webp',
  '.woff': 'application/font-woff',
  '.woff2': 'application/font-woff2',
  '.woff3': 'application/font-woff',
  '.xls': 'application/vnd.ms-excel',
  '.xlsx': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  '.xml': 'text/xml',
  '.yaml': 'application/x-yaml',
  '.zip': 'application/zip'
}

export function getExtensionContentType(ext: string): string {
  return EXTENSIONS_ENUM[ext] || 'text/plain'
}
